[platformio]
default_envs = nm-tv-154

[env:nm-tv-154]
platform = espressif32@6.6.0
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_port = COM9
upload_port = COM9
board_build.filesystem = littlefs
board_build.partitions = ota.csv
extra_scripts = post:scripts/generate_full_image.py
board_build.f_cpu = 240000000L
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DNMTV154_BOARD
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DLOAD_GLCD=1
    -DCGRAM_OFFSET
    -DUSE_HSPI_PORT
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=240
    -DTFT_MOSI=13
    -DTFT_SCLK=14
    -DTFT_CS=15
    -DTFT_DC=2
    -DTFT_RST=-1
    -DSPI_FREQUENCY=40000000
    -DSPI_READ_FREQUENCY=20000000
lib_deps =
    Bodmer/TFT_eSPI
    bblanchon/ArduinoJson @ ^7.0.0
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer
