#pragma once

#define NVS_KEY_WIFI_SSID       "wifi_ssid"
#define NVS_KEY_WIFI_PASSWORD   "wifi_pass"
#define NVS_KEY_LAT             "lat"
#define NVS_KEY_LON             "lon"
#define NVS_KEY_CITY            "city"
#define NVS_KEY_TIMEZONE        "tz_offset_min"
#define NVS_KEY_EYE_COLOR       "eye_color"
#define NVS_KEY_COLOR_CYCLE     "color_cycle"
#define NVS_KEY_CUSTOM_COLOR    "custom_color"
#define NVS_KEY_ROUND_EYE       "round_eye"
#define NVS_KEY_UNITS_TEMP      "units_temp"
#define NVS_KEY_UNITS_SPEED     "units_speed"
#define NVS_KEY_UNITS_PRES      "units_pres"
#define NVS_KEY_UNITS_DIST      "units_dist"
#define NVS_KEY_UNITS_PRECIP    "units_precip"
#define NVS_KEY_TIME_FORMAT     "time_format"
#define NVS_KEY_DATE_FORMAT     "date_format"
#define NVS_KEY_LANGUAGE        "language"
